### ISSUE TITLE
New Install Missing Permissions

### ISSUE THREAD

**Issue by pricenfi** [KelvinTegelaar/CIPP#1031]
### Description

1. Setup new instance
2. Use wizard to create secure app token
3. Wait for things to update
4. Go to settings and run permission check
5. Receive the following error

Your Secure Application Model is missing the following delegated permissions:
- Policy.ReadWrite.ApplicationConfiguration
- SecurityIncident.Read.All
- SecurityIncident.ReadWrite.All

### Environment data

```PowerShell
Azure Instance using Click to Deploy
```

**Comment by pricenfi** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

Additionally, there is no mention of these permissions in the docs (https://cipp.app/docs/user/gettingstarted/permissions/)

**Comment by syndeso** [comment]
> I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.
> 
> Additionally, there is no mention of these permissions in the docs (https://cipp.app/docs/user/gettingstarted/permissions/)

I encountered the same permissions issues. In addition, I was also missing SharePointTenantSettings.ReadWrite.All. 

I fixed all missing permissions manually by following the documentation in the link above. I made sure to Grant the permissions after adding these missing entries, and restarted the Function App. I returned to my instance and all permission checks passed successfully.

**Comment by KelvinTegelaar** [comment]
added in dev

**Comment by jpeerbolte** [comment]
I just did a clean deployment exactly like pricenfi described in this bug report.

Frontend 2.11.0
Backend 2.0.0

After the post-configuration I run a Permissions Check and get the following output:

Your access token contains the MFA claim.
Your Secure Application Model is missing the following delegated permissions:
- Policy.ReadWrite.ApplicationConfiguration
- SecurityIncident.Read.All
- SecurityIncident.ReadWrite.All

Should this have been fixed already as the bug is closed?
