### ISSUE TITLE
MFA Push Fails while showing a green success banner incorrectly

### ISSUE THREAD

**Issue by knightian** [KelvinTegelaar/CIPP#1126]
### Description

When sending a user a "Send MFA Push" in the User view, if the user does not have a default MFA method which sends them a push notification/phone call proactively, the MFA Push fails however it shows a green success box with an error code of "success".

An example of a non-proactive MFA option is a TOTP code from Google Authenticator (or even in the Microsoft you can have TOTP).

![image](https://user-images.githubusercontent.com/72685601/190901681-513ce464-847a-42b3-8fca-197a8a25d3d4.png)

Expected behaviour:

Show an error message that doesn't suggest success i.e. Red banner, error code displayed (bonus points if we can show the reason why it errored i.e. incorrect default MFA type)

What would be even better is if we can iterate the MFA options available and use the push/phone even if it is not the default, I do not know if that is possible though.

### Environment data

```PowerShell
dev
```

**Comment by KelvinTegelaar** [comment]
Not possible. The API is not aware and cannot change the mfa method. This is just how that API responds. Sending the request is successful, but acknowledgement is not, which is why it says Authentication Failed. 

I'll see if we can change the colour to red when it happens though, that should help make a little bit more clear it failed.
