### ISSUE TITLE
Offboarding Wizard fails if UPN does not match email address

### ISSUE THREAD

**Issue by drew5901** [KelvinTegelaar/CIPP#1212]
### Description

1) Run offboarding wizard
2) Select tenant, select user, select options, run wizard
3) Receive error that "An error has occurred: Resource '<email address>' does not exist or one of its queried reference-property objects are not present" 403 - Request failed with status code 403

This users UPN is not the same as the users email address. The account does sync to O365 from an on-prem AD via AD connect. The only options selected should be able to be managed in O365 without changing anything in Active Directory unless is errors out because "remove from all groups" would include groups from AD.

### Environment data

```PowerShell
hosted in Azure
```

**Comment by KelvinTegelaar** [comment]
The issue that the users UPN does not match their primary email address is actually an issue for MS's side too; this is an unsupported M365 configuration since recently. If you really want to have unmatching UPNs Microsoft recommends this article to understand all the limitations that you'll have: 

https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#what-is-alternate-login-id

So to summerize; this is an unsupported/not recommended M365 configuration, and thus not a CIPP issue.
