### ISSUE TITLE
[Feature Request]: MFA Report to include enrolled methods and default method

### ISSUE THREAD

**Issue by Novem-MSP** [KelvinTegelaar/CIPP#1691]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Within the MFA report, I would like to see the inclusion of the enrolled methods users have and the default method used. 

### PowerShell commands you would normally use to achieve above request

To return authentication methods you can use the following
microsoft.graph.softwareOathAuthenticationMethod
https://learn.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods

There is also a report that should provide most of this information along with a Powershell script here 
https://o365reports.com/2022/04/27/get-mfa-status-of-office-365-users-using-microsoft-graph-powershell/

**Comment by KelvinTegelaar** [comment]
> There is also a report that should provide most of this information along with a Powershell script here
https://o365reports.com/2022/04/27/get-mfa-status-of-office-365-users-using-microsoft-graph-powershell/

This report is famously inaccurate and lists *any* device the user has even registered, even if MFA is disabled on their account this report will still state it's enabled as there is a device in the list. 

The reason this isn't in the reports is because it will break the report for non-p1/p2 subscribers, so this is a wontfix for now. :)
