### ISSUE TITLE
Set BPA and Standard Application Times and Frequency

### ISSUE THREAD

**Issue by DarrenChap** [KelvinTegelaar/CIPP#174]
**Is your feature request related to a problem? Please describe.**
Having to either wait or do mental arithmetic to work out when the BPA scan or the Standard Application task run is a bit painful.

**Describe the solution you'd like**
A place to set the time (preferably in local timezone but that may be difficult) of when the BPA and Standard Application tasks run.  

If not a setting then at least a display of next run time....in local time (as mentioned in Slack I believe).

**Comment by gavsto** [comment]
So we can force the running of it pretty easily (there's already a button to do that for BPA). I don't think though we can change the time that it is running. That's hardcoded in to the function. @KelvinTegelaar what happens if we overwrite the cron in the function in runtime? Will it take or will it not work until a function app reboot?

**Comment by KelvinTegelaar** [comment]
Won't work. I think we can do two things; create a "Force Standards now" button, and a "Next run at" thingy. I think that covers what @DarrenChap is looking for?

**Comment by DarrenChap** [comment]
Yep that would do the job as well.

**Comment by KelvinTegelaar** [comment]
added force standards button in dev, and display that it runs every 3 hours.
