### ISSUE TITLE
UPN Field changing by default to pull "mail.nickname" attribute without asking

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#2263]
### Description

We have noticed an urgent critical issue with CIPP

We have noticed when editing a user in CIPP, the user details page changes their username to their mail-nickname without asking for input, this is very dangerous for us, as it happens even when we arent touching the username field, even when we are just changing a license

### Environment data

```PowerShell
Self hosted
Sponsor
5.3.2
```

**Comment by KelvinTegelaar** [comment]
This is expected behaviour in the Graph API. Microsoft no longer supports a difference between the UPN and mailnickname attribute. Any modern portal(eg the beta admin portal or beta exchange portal) will cause the same behaviour.

If you require the mailnickname to be different than the upn, microsoft documentation states you can setup alternate login ID using adfs. More info here: https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id

**Comment by cardonet-helpdesk** [comment]
this might be the case, but who asked CIPP to start changing fields that we arent asking it too?
