### ISSUE TITLE
[Feature Request]: Combined Identity and Mailbox Report

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2467]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

There are many occasions when it is helpful to look at both identity information (such as UPN, sign-in status, and license) alongside mailbox information (such as mailbox type [Shared/User], Last Active, and Used space). Currently I export the Identity > Users report as well as the Email & Exchange > Mailbox Statistics reports and use Excel lookups to get a combined report.

My request would be to have a report that includes both Identity and Mailbox information in a single report. The UserPrincipalName is a unique identifier that can connect the two existing reports together.

Examples of areas where a combined report would be very helpful:

- Find shared mailboxes associated with a licensed user account (license could be removed without affecting mailbox if it is <50GB)
- Find user accounts that are disabled but have a user mailbox (which could be converted to a shared mailbox)
- Find user mailboxes that unnecessarily have Exchange Plan 2 licenses (and could be downgraded to Exchange Plan 1 if mailbox is under 50GB)
- Find user accounts that are disabled and have no license. (If we saw that a mailbox existed, we would keep the account for its shared mailbox, but otherwise we could know to delete the account since it had no associated mailbox.)
- Find enabled user accounts with a license assigned but without a recent Last Active date (we might find users that should have been terminated but were not)
- Find user accounts without a license but still associated with a User Mailbox (I'm not sure what circumstances lead to this, but there are times when a User Mailbox remains present even when a license has been removed)

These scenarios could be setup as pre-defined filters as well. If this could be setup to work in the *All Tenants view, we could rapidly find the above situations across all our customers which would be extremely powerful.

**Comment by KelvinTegelaar** [comment]
While this isn't coming anytime soon - We're working on the background on some of these tasks, for now we're closing this as it's going to be pretty hard to implement and our priorities are on current roadmap items, however feel free to reopen at a later date!

**Comment by simislearning** [comment]
that's complex reporting but interesting  that's more of proactive work you are doing though  but won't be same for all MSP's though. This where RPA can come handy for these types of tasks. 


1. Find shared mailboxes associated with a licensed user account (license could be removed without affecting mailbox if it is <50GB) - This will be ideal for all MSP's
2. Find user accounts that are disabled but have a user mailbox (which could be converted to a shared mailbox)  - This will be ideal for all MSP's
3. Find user mailboxes that unnecessarily have Exchange Plan 2 licenses (and could be downgraded to Exchange Plan 1 if mailbox is under 50GB)  - This won't be ideal for all users mailboxes since E2 can be used for litigation hold or something else
4. Find user accounts that are disabled and have no license. (If we saw that a mailbox existed, we would keep the account for its shared mailbox, but otherwise we could know to delete the account since it had no associated mailbox.)  - This will be ideal for all MSP's
5. Find enabled user accounts with a license assigned but without a recent Last Active date (we might find users that should have been terminated but were not) - This will be ideal for all MSP's
6. Find user accounts without a license but still associated with a User Mailbox (I'm not sure what circumstances lead to this, but there are times when a User Mailbox remains present even when a license has been removed)  - This will be ideal for all MSP's
