### ISSUE TITLE
[Feature Request]:  Set mailboxes to always show from field

### ISSUE THREAD

**Issue by mriga277** [KelvinTegelaar/CIPP#2755]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I have a number of customers who are heavily dependent on shared mailboxes. 
One of the problems is new staff struggling to work how to send as someone else (typically the shared mailbox) 
Frontline workers are the main culprit. 
Having a standard to apply the always show from field would make life a little easier to them, and there for us. 

### PowerShell commands you would normally use to achieve above request

GetMailbox | Set-MailboxMessageConfiguration -AlwaysShowFrom $True

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
We discussed this in the dev team, and decided to have added this not as a standard, but something you can set up for individual customers via the scheduler.  
This functionality is very costly time/processing wise, since it needs to loop through all mailboxes in the tenant and not just set a tenant wide setting.

**Comment by KelvinTegelaar** [comment]
And added in dev :)
