### ISSUE TITLE
Editing calendar permissions fails if user added to calendar has a personal Microsoft account

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2963]
### Description

1. Disable External calendar sharing
2. Wait 1 Microsoft minute
3. Find user with personal MS account with the same UPN
4. Find a random user to add permissions to
5. Try to add/edit/remove the user with the personal MS account permissions, from the random users calendar
6. Observe the success it returns but no edits have been made. The $CalParam.Identity in the return message is blank for some reason.

This happens cause for some reason, the personal account take precedence over the internal user in the tenant. Very odd why this happens. 
Changing to use ExternalDirectoryObjectId instead, will make EXO understand that we mean the internal user in the tenant, and not the external personal MS account.

### Environment data

```PowerShell
Sponsored instance
Frontend: 6.4.1
Backend: 6.5.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by kris6673** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by kris6673** [comment]
Gonna fix this after the frontend rewrite, since it requires a change in the frontend

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have identified the issue with calendar permissions for users with personal Microsoft accounts. The problem occurs because the personal account takes precedence over the internal user in the tenant. To resolve this, I've modified the `EditCalendarPermissions.jsx` file to use the `ExternalDirectoryObjectId` instead of the UPN when adding or removing calendar permissions. This change will ensure that Exchange Online understands we are referring to the internal user in the tenant, not the external personal Microsoft account.

I also created pull request: https://github.com/KelvinTegelaar/CIPP/pull/2964

> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by kris6673** [comment]
> Hello, I've fixed this issue!
> 
> This is what I've done: I have identified the issue with calendar permissions for users with personal Microsoft accounts. The problem occurs because the personal account takes precedence over the internal user in the tenant. To resolve this, I've modified the `EditCalendarPermissions.jsx` file to use the `ExternalDirectoryObjectId` instead of the UPN when adding or removing calendar permissions. This change will ensure that Exchange Online understands we are referring to the internal user in the tenant, not the external personal Microsoft account.
> 
> I also created pull request: #2964
> 
> Caution
> 
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> This bug was fixed for free by Latta AI - https://latta.ai/ourmission

Very close, but you need to add ExternalDirectoryObjectId to the returned parameters in Modules\CIPPCore\Public\Entrypoints\Invoke-ListMailboxes.ps1 too, otherwise ExternalDirectoryObjectId will be missing from the table in the frontend
