### ISSUE TITLE
Custom Roles removes *All Tenants

### ISSUE THREAD

**Issue by MalcolmReynoldsWrap** [KelvinTegelaar/CIPP#2965]
### Description

When applying a custom role (billing) that has readonly access to everything except the scheduler to build reports the *All Tenants option will disappear for the user. I have verified that the role has access to *All Tenants in the configuration. The user can access everything else normally, but is missing *All Tenants across every page within CIPP.

### Environment data

```PowerShell
Non-Sponsored.
Frontend: 6.4.1
Backend: 6.5.2
Tried Tenant Cache Clear:True
Tried Token Cache Clear:True

Billing role settings:
Allowed Tenants

    *All Tenants

Selected Permissions

    CIPP.Alert.Read
    CIPP.AppSettings.Read
    CIPP.Backup.Read
    CIPP.Core.Read
    CIPP.Extension.Read
    CIPP.Scheduler.ReadWrite
    CIPP.SuperAdmin.Read
    Endpoint.Application.Read
    Endpoint.Autopilot.Read
    Endpoint.Device.Read
    Endpoint.MEM.Read
    Exchange.Connector.Read
    Exchange.Contact.Read
    Exchange.Group.Read
    Exchange.Mailbox.Read
    Exchange.Room.Read
    Exchange.SpamFilter.Read
    Exchange.TransportRule.Read
    Identity.AuditLog.Read
    Identity.Device.Read
    Identity.Group.Read
    Identity.Role.Read
    Identity.User.Read
    Scheduler.Billing.ReadWrite
    Security.Alert.Read
    Security.Incident.Read
    Sharepoint.Admin.Read
    Sharepoint.Site.Read
    Teams.Activity.Read
    Teams.Group.Read
    Teams.Voice.Read
    Tenant.Administration.Read
    Tenant.Alert.Read
    Tenant.Alerts.Read
    Tenant.Application.Read
    Tenant.BestPracticeAnalyser.Read
    Tenant.ConditionalAccess.Read
    Tenant.DeviceCompliance.Read
    Tenant.Directory.Read
    Tenant.DomainAnalyser.Read
    Tenant.Relationship.Read
    Tenant.Standards.Read
```

**Comment by MalcolmReynoldsWrap** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for reaching out! This report has been classified as a support request rather than a bug report. To keep our development process focused, support requests are limited to paying users. This policy allows us to prioritize resources for those actively supporting CIPP, helping us maintain high-quality development and support.

Sponsors can contact our helpdesk directly via email for assistance with any issues or questions. For non-sponsor support, please refer to our documentation and community discussions, where you may find answers to similar queries.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment, and we’ll gladly reopen the request.

Thank you for your understanding,
The CIPP Team
