### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by brianman108** [KelvinTegelaar/CIPP#2982]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Looking for a custom role or other means to scope permissions to change global admin users account password but still be able to reset normal users. The goal is to allow our helpdesk to use CIPP without giving them the ability reset our client's GA's

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for reaching out! This report has been classified as a support request rather than a bug report. To keep our development process focused, support requests are limited to paying users. This policy allows us to prioritize resources for those actively supporting CIPP, helping us maintain high-quality development and support.

Sponsors can contact our helpdesk directly via email for assistance with any issues or questions. For non-sponsor support, please refer to our documentation and community discussions, where you may find answers to similar queries.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment, and we’ll gladly reopen the request.

Thank you for your understanding,
The CIPP Team

**Comment by brianman108** [comment]
> Hello,
> 
> Thank you for reaching out! This report has been classified as a support request rather than a bug report. To keep our development process focused, support requests are limited to paying users. This policy allows us to prioritize resources for those actively supporting CIPP, helping us maintain high-quality development and support.
> 
> Sponsors can contact our helpdesk directly via email for assistance with any issues or questions. For non-sponsor support, please refer to our documentation and community discussions, where you may find answers to similar queries.
> 
> Did you get this notification in error? Reply with a screenshot of your sponsorship payment, and we’ll gladly reopen the request.
> 
> Thank you for your understanding, The CIPP Team

![image](https://github.com/user-attachments/assets/4884f937-61f5-4a0f-8fd7-1d621c53e6dc)
