### ISSUE TITLE
CIPP unable to sync to NinjaOne

### ISSUE THREAD

**Issue by AmineKorichi** [KelvinTegelaar/CIPP#3027]
### Description

We are trying to integrate CIPP to NinjaOne for our internal tenant first before moving on to a broader deployment for our customers. We have followed the guides provided by CIPP and deployed on our azure environment. The tenant is fully synced in CIPP, the issue basically seems to stem from a failed sync.
![Screenshot 2024-12-30 131419](https://github.com/user-attachments/assets/762ea48b-c9bb-4df1-9563-8e70cd1fc062)

Any ideas on what could be causing this? NinjaOne support does not provide any assistance with this and says that it does not support the integration. Any logs even I could look at to point me to the right direction or is this a bug?

Thanks,

### Environment data

```PowerShell
Non-Sponsored instance
Front end version: 6.4.1
Backend version: 6.5.4
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for reaching out! This report has been classified as a support request rather than a bug report. To keep our development process focused, support requests are limited to paying users. This policy allows us to prioritize resources for those actively supporting CIPP, helping us maintain high-quality development and support.

Sponsors can contact our helpdesk directly via email for assistance with any issues or questions. For non-sponsor support, please refer to our documentation and community discussions, where you may find answers to similar queries.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment, and we’ll gladly reopen the request.

Thank you for your understanding,
The CIPP Team
