### ISSUE TITLE
BUG: [React] [UX] - Email details in user information is breaking out of its bordered box

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#626]
![image](https://user-images.githubusercontent.com/3102057/149813601-bdb1b8a9-2ec2-4b30-8bec-17375212fd28.png)

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@KelvinTegelaar target 2.0.1

**Comment by KelvinTegelaar** [comment]
I think this is fixed, at least I don't see it happening in my instance. @gavsto do you?

**Comment by homotechsual** [comment]
@gavsto can you recheck this on dev?

**Comment by johnduprey** [comment]
I'm seeing this in my environment as well. It's mostly the onmicrosoft.com domains since the "word" is rather long and does not break properly. I have a couple thoughts on how to address it:
- We could the Aliases property in API to strip out the smtp: part of the string (also remove primary address since that's in another property. That'll shorten the string enough in most cases.
```$_.Aliases = ($_.ProxyAddresses | Where-Object { $_ -CMatch '^smtp:(?<Email>.+)' } | ForEach-Object { $Matches.Email }) -join ', '```
- We could present the alias emails in their own card so that the email address isn't sharing space with the Proxy Addresses header on each list group item.

**Comment by homotechsual** [comment]
Can we just return the aliases as an array instead of joining them to a string? That way we can handle the display on the frontend nicely?
