### ISSUE TITLE
FEATURE REQUEST: display tenant name in Domain Analyzer page

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#687]
**Is your feature request related to a problem? Please describe.**
When managing many (tens/hundres) of tenants, dome of them with multiple domains, it's useful to sort/filter/manage domains per tenant/customer 

**Describe the solution you'd like**
Add a Tenant name column in Domain Analyzer page. Optionally, a filter field to display only domains for the selected Tenant

**Describe alternatives you've considered**
A sepparate excel file with tenant / domains mappings :)

**Additional context**

**Comment by servant42** [comment]
We have a lot of tenants with multiple domains. Would love to go further and have the tenant name group the domains and be able to expand/collapse visible domains by tenant. Being able to filter the list by tenant name would be similar, though.

Right now because we have tenants under different levels of management, it's not easy to confirm the domains associated with fully managed tenants all being consistently configured while ignoring domains that we don't have full management over.

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@KelvinTegelaar implemented for 2.1
