### ISSUE TITLE
BUG: clicking "atypical travel" alert goes to a 404 page

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#839]
**Describe the bug**
when I click this "atypical travel" alert on a customer tenant, I get to this 404 page:
![image](https://user-images.githubusercontent.com/17422069/159188083-b0b839da-d22e-464e-be8b-613aa7b6ff8a.png)
![image](https://user-images.githubusercontent.com/17422069/159188085-0c674766-9a11-4218-9fd1-5d5cfa6d8e35.png)
That 404 page is our custom domain then /security/reports/undefined

**To Reproduce**
Go to Security & compliance > List alerts > select a client tenant > click on the 👁 symbol next to an "atypical travel" alert and then in the Alert Information flyout click "👁 View source alert in compliance center"

**Expected behavior**
It takes us to the specific alert page in client's compliance center

**Desktop (please complete the following information):**

- OS: Windows 10 Pro, latest version
- Browser: Edge

**Comment by gavsto** [comment]
So.... this is expected behaviour as I understand it though I am not sure why our UI is allowing for it to be a clickable link. There is currently no delegated access to the area where these alerts are so we can't do a click through URL.

@KelvinTegelaar you added this in - did you have something in mind with it or should we make this copy the URL to clipboard instead of linking?

**Comment by dan-baird** [comment]
Go with providing a way to copy URL to clipboard, that's a great solution.

**Comment by KelvinTegelaar** [comment]
Should be a direct URL yes, but removing this feature while GDAP is here yet. :)
