### ISSUE TITLE
Feature request: List / Add / Edit / Remove Contacts

### ISSUE THREAD

**Issue by freezscholte** [KelvinTegelaar/CIPP#90]
**Is your feature request related to a problem? Please describe.**
Also another one from our support guys, is to list and edit the contacts list that you can find in admin center and EXO admin center.

**Describe the solution you'd like**
In the Identity menu a submenu button to list/add/edit/remove contacts

**Describe alternatives you've considered**
Currently using admin.microsoft.com

**Comment by lwhitelock** [comment]
It turns out the Contacts APIs available are pretty useless, either read only, insanely rate limited, or interactive sessions only. The only practical option was the graph read only list. I have added in the ability to view contacts using that API and then edit them directly in exchange admin centre with a link. I think this is the best option until MS improves things.

**Comment by KelvinTegelaar** [comment]
Added as read-only until Graph improves. Now functional in the dev build. :)
